### ISSUE TITLE
Add starred projects to index

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#115]
sadly there is no direct way of retrieving pinned repositories on Github. 
The only way I can think of is by creating a notion database and add them to it.
I'll use the notion api to get the data to my website

**Comment by Ryuno-Ki** [comment]
Well … https://docs.github.com/en/rest/reference/activity#list-repositories-starred-by-a-user

Or with some filtering on http://github.com/inezabonte.atom as described in https://stackoverflow.com/a/44187356

**Comment by inezabonte** [comment]
Sorry 🤦🏾‍♂️ I meant pinned. The repositories that I've pinned to my profile. Starred repositories will include even those which aren't mine.

**Comment by inezabonte** [comment]
Just Got an idea. I'll just star the repositories then filter the ones that belong to me
