### ISSUE TITLE
Create a Digital Garden 🌱

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#122]
I sometimes come across interesting articles. Like tutorial that I would like to save for the future.
I could save them on a page somehow 🤔

**Comment by Ryuno-Ki** [comment]
Yay, for another toolbox page!

I saw some people starting collecting these under a /til (= today I learned) path.

**Comment by inezabonte** [comment]
@Ryuno-Ki That's a great Idea. I also recently saw /garden (a digital garden) basically like a journal where you write or post things in off your mind what you learned or ideas in no particular order

**Comment by inezabonte** [comment]
I'll experiment with Storybook

**Comment by inezabonte** [comment]
[Nextra](https://nextra.vercel.app/) seems nice and less complex as compared to Storybook.
And it's Next.js based

**Comment by inezabonte** [comment]
Will be working on it through this [repo](https://github.com/inezabonte/digital-garden)
