### ISSUE TITLE
Style the headshot

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#131]
I recently received a suggestion from @renepromesse to make my headshot circular and give it a white border.
Let's try this and see how it turns out
<img width="324" alt="Screen Shot 2021-05-31 at 19 00 39" src="https://user-images.githubusercontent.com/33348046/120223819-7f0b2900-c242-11eb-89e6-3c24e0a4d1b1.png">

**Comment by inezabonte** [comment]
Hmm, could work 🤔

Dark
![Screen Shot 2021-05-32 at 21 05 49](https://user-images.githubusercontent.com/33348046/120232558-14fb7f80-c254-11eb-91f9-e2d2d85d5538.png)

Light
![Screen Shot 2021-05-32 at 21 07 17](https://user-images.githubusercontent.com/33348046/120232612-3492a800-c254-11eb-9fc1-489b031551ca.png)

**Comment by renepromesse** [comment]
@inezabonte looks great, how do you see the grey border in light mode? did you test black (this color of text?)  🎉🎉
