### ISSUE TITLE
Add nosnippet meta tag

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#148]
If you do a google search of my name. This is how my portfolio shows up.
<img width="668" alt="Screen Shot 2021-06-16 at 23 32 46" src="https://user-images.githubusercontent.com/33348046/122297280-9feaa400-cefb-11eb-82af-fb94da3ff20b.png">

Google automatically generates a desrciption from the content on your index page.
It doesn't do a great job at describing what your website is about. 

The `nosnippet` meta tag stops google from taking content from your page and use the appropriate description meta tag

**Comment by Ryuno-Ki** [comment]
Perhaps also worth to look into schema.org / JSON-LD definitions for breadcrumbs or so.
