### ISSUE TITLE
Issue caused by aria-labelledby

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#149]
https://github.com/inezabonte/inezabonte/blob/46e6e0a58dc78a1643ce15ba77d2dc88b7960d1f/components/NavBar.js#L24-L35

For some Reason I keep getting this error message. It's coming from the aria-label. 
<img width="787" alt="Screen Shot 2021-06-18 at 15 00 12" src="https://user-images.githubusercontent.com/33348046/122564648-e51aed00-d045-11eb-8a59-82c251c8b203.png">

**Comment by Ryuno-Ki** [comment]
I believe, this is correct.

As far as I can tell,

https://github.com/inezabonte/inezabonte/blob/cd111ca29dfb9760be5178909f781f0a6c1cf0da/pages/_app.js#L6

does not set a default theme.
Thus, `resolvedTheme` is likely `undefined`. `undefined === "dark"` is falsy. Thus, I would expect the value to be `Switch to dark mode` by default.

It could be that the client supports a media query for `prefers-color-scheme: dark;` and gives you another result.

**Comment by inezabonte** [comment]
Yes true resolvedTheme becomes available when the components are mounted 
so this was a case of hydration mismatch error
