### ISSUE TITLE
Add fonts to repo

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#154]
Adding fonts to the project will reduce load time and also
 they will be accessible in case I happen to code offline

**Comment by Ryuno-Ki** [comment]
https://www.zachleat.com/web/css-tricks-web-fonts/ might come in handy.
Check the license of the fonts, though, to see, whether you can subset them.

**Comment by inezabonte** [comment]
The font I'm using(Fira Sans) is licensed under Open Font License (OFL)
 so I can pretty much do anything I want with it except selling the font itself
