### ISSUE TITLE
Convert project to Typescript

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#169]
Shifting to typescript will help me enforce the TS basics as I learn how to work with it alongside react

**Comment by inezabonte** [comment]
What's up @Ryuno-Ki ?

**Comment by Ryuno-Ki** [comment]
I'm vocal opponent of TypeScript, as it adds a lot of bloat in the compiled output for little gain.
However, it grew in popularity, so picking a side project (like one's homepage) might be a good idea to train one's skill.

It's yours.

I will go with https://gils-blog.tayar.org/posts/jsdoc-typings-all-the-benefits-none-of-the-drawbacks/ for my projects.

**Comment by inezabonte** [comment]
I was looking for ways that could help me to learn Typescript.
I decided to use my other side projects [My weather app](https://github.com/inezabonte/WeatherApp), [My joke generator](https://github.com/inezabonte/jokegenerator) currently working on the [the todo app](https://github.com/inezabonte/todo-app)
I'll use those for the learning process and experimenting typescript ideas instead of dragging my 
flagship project into it.

**Comment by Ryuno-Ki** [comment]
Let me know if you need help there.
By now, I got familar with TypeScript, so I can answer questions, I guess.
