### ISSUE TITLE
Add contrast to footer text

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#171]
The text in the footer needs a bit more contrast
<img width="508" alt="Screen Shot 2021-07-27 at 16 22 57" src="https://user-images.githubusercontent.com/33348046/127171114-4af3e24d-2026-4687-92f9-18e0cba944a7.png">

**Comment by Ryuno-Ki** [comment]
Indeed: https://coolors.co/contrast-checker/6b7280-111827 recommends `#BFC3CA`.

**Comment by inezabonte** [comment]
Any ideas on how I can solve this? @Ryuno-Ki 
<img width="682" alt="Screen Shot 2021-07-28 at 00 26 26" src="https://user-images.githubusercontent.com/33348046/127235652-af4fdee4-8cc0-49d5-94d7-15c6bbf294fb.png">

**Comment by Ryuno-Ki** [comment]
While `aria-label` works, it has some downsides.
If I use automatic-translation as offered by some browsers, chances are it won't get covered.

Instead, a `.sr-only` helper class is a better choice: https://webaim.org/techniques/css/invisiblecontent/

**Comment by inezabonte** [comment]
Awesome, I'll use this approach
