### ISSUE TITLE
Consider using Sanity as a CMS

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#176]
With Sanity I will have a more organised way of updating content (especially articles)
since every time I have to create a pull request for any mistakes I may spot in my content.

It will also handle image uploading for me. I won't have to upload each of them individually to cloudinary.

In the schemas I'm able to add a markdown editor to write my blogs which is cool.

**Comment by Ryuno-Ki** [comment]
Research how to make backups or pull out your content in case you ever want to move away from there …

**Comment by inezabonte** [comment]
It is possible to export it into .ndjson format 🤔

**Comment by Ryuno-Ki** [comment]
Great!

I found CMS that made it a bit harder to migrate. That's why I said, do some research upfront before investing in a solution.

**Comment by inezabonte** [comment]
Hmmm.... This will also mean that I have to use server side rendering for the pages. Which will be terrible for performance.
Aaaaaaah
![Morpheus holding two pills](https://i.pinimg.com/originals/42/08/12/420812adcf6aa0e3185f09679de0355b.jpg)

**Comment by Ryuno-Ki** [comment]
Looking forward to your own CMS :grimacing:

**Comment by inezabonte** [comment]
Nextjs has Incremental Static Regeneration. Though the regenerate property in `getStaticProps`.
We're still good 
![A person showing relief](https://media.giphy.com/media/YucHVxk7WYIc8/giphy.gif)

**Comment by inezabonte** [comment]
After using Sanity for a while in my garden I have come to reconsider my decision; Sanity may not be the best
option for this site. One reason being that I'm not able to use components inside the content I write

**Comment by inezabonte** [comment]
Looking back 2 years ago the reason I had for **not** migrating was not valid enough. 
I will be making the move.
