### ISSUE TITLE
Add charset meta element

### ISSUE THREAD

**Issue by Ryuno-Ki** [inezabonte/inezabonte#68]
Adding a `<meta charset="utf-8" />` ensures, that the document is correctly parsed and interpreted:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset

It should appear after the `<head>`:

https://github.com/inezabonte/inezabonte/blob/87cec61b28583a756cfcf19da5ba6084b48fcd13/components/Header.js#L6

**Comment by inezabonte** [comment]
It seems like Next.js adds it automatically. Through the Head component in the `pages/_document.js` file.
<img width="418" alt="Screen Shot 2021-04-30 at 12 20 44" src="https://user-images.githubusercontent.com/33348046/116682442-8c689580-a9ae-11eb-97f2-c77c1676286e.png">

**Comment by Ryuno-Ki** [comment]
True. I can see it twice now :see_no_evil:
