### ISSUE TITLE
Specify type of buttons

### ISSUE THREAD

**Issue by Ryuno-Ki** [inezabonte/inezabonte#70]
By default, the `type` of a `<button>` is submit.
I'd argue it's good practice to be explicit, e.g. in

https://github.com/inezabonte/inezabonte/blob/87cec61b28583a756cfcf19da5ba6084b48fcd13/components/NavBar.js#L40-L45

**Comment by inezabonte** [comment]
What type should I give it?

**Comment by Ryuno-Ki** [comment]
`type="button"`
