### ISSUE TITLE
Experiment with a new Font

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#74]
The current font looks bold by default which somehow doesn't provide a clear difference between normal text and titles

**Comment by Ryuno-Ki** [comment]
You might want to give https://fontjoy.com/projector/ a shot. (Please read https://fontjoy.com/pairing/ to aid in finding a good fit).

If I look at https://fonts.google.com/specimen/Josefin+Sans#pairings Raleway might be a good pairing.
Or pick another font from the same designer: https://fonts.google.com/?query=Santiago+Orozco
Looks like it has a Swedish history: https://github.com/googlefonts/josefinsans

https://www.fontspace.com/category/african might have some fonts for decorative parts.

**Comment by inezabonte** [comment]
I think I'll stick with the current one for now. Might reconsider re-opening in the future
