### ISSUE TITLE
Categorize articles

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#81]
Split articles according to the year in which they were created

**Comment by Ryuno-Ki** [comment]
I couldn't hold myself back => #82

**Comment by inezabonte** [comment]
@Ryuno-Ki check mate => #83

**Comment by Ryuno-Ki** [comment]
Can we find a middle ground?

**Comment by inezabonte** [comment]
- I think. I prefer the dynamic approach I did, so that I don't have to always update it manually. I actually copied your code for filtering  part😅. 
 - Then from your branch I can get the change you made to the parser getting the rss feed
 - I'll merge your branch for now to get those changes on the parse then after I'm done styling I'll solve the conflicts then merge mine

**Comment by Ryuno-Ki** [comment]
![sounds like a plan](https://i.imgflip.com/17bhi4.jpg)
