### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by Ryuno-Ki** [inezabonte/inezabonte#84]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates

Otherwise, we lack cats! (See https://github.com/inezabonte/inezabonte/pull/82#issuecomment-830839479 )

Idea: https://github.com/lirantal/is-website-vulnerable/blob/b9bcf0e39efa895979f66e5b7edb2809d23878bf/.github/PULL_REQUEST_TEMPLATE.md

**Comment by inezabonte** [comment]
Got it
