### ISSUE TITLE
More Data on Home page

### ISSUE THREAD

**Issue by inezabonte** [inezabonte/inezabonte#96]
- I need more data on the home page. Could be my projects or my resume 🤔
- But I think projects need their own separate page
- Or I could add my features  in the newspaper
- Latest articles I wrote

**Comment by Ryuno-Ki** [comment]
Around last year, Danny was asking for homepages: https://twitter.com/DThompsonDev/status/1257683425248645120
Perhaps you can look at some of those to get an idea?
(Link rot is strong on that threads)

**Comment by inezabonte** [comment]
Great thanks. I needed this.

**Comment by Ryuno-Ki** [comment]
I steal back from you once you figured out what to put on a portfolio, mkay? :D

**Comment by inezabonte** [comment]
Sharing is caring 😉

**Comment by inezabonte** [comment]
This list will grow overtime as I get more inspirations
 - https://sebastianhamalainen.com/

**Comment by Ryuno-Ki** [comment]
Looks like a good start! I'd suggest to keep it as wiki on this repo?

**Comment by inezabonte** [comment]
Great idea

**Comment by inezabonte** [comment]
https://github.com/inezabonte/inezabonte/wiki/Inspirations

**Comment by Ryuno-Ki** [comment]
Don't forget the screenshots!
(Or put the page onto archive.org)

They might change their design at any point.

**Comment by inezabonte** [comment]
I'll do that

**Comment by inezabonte** [comment]
On the home page I will add;
- a section showing my latest three articles
- a section showing some of best projects and also

This should be enough for now
